version: '3.3'

services:
  nuxt:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    image: nuxt_build
    platform: linux/x86_64 # Extremely slow build times with this prop attached, try building on a PC
    container_name: nuxt_app
    ports: 
      - "3000:3000"
  db: 
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    image: db_prod
    platform: linux/x86_64 # Extremely slow build times with this prop attached, try building on a PC
    environment:
      - ASPNETCORE_URLS=http://+:9362:80
    container_name: db_api
    ports: 
      - "9362:80"

