FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /db

COPY backend/*.sln .
COPY backend/*.csproj .

RUN dotnet restore

COPY backend/. .
RUN dotnet publish -c Release -o /app --no-restore --use-current-runtime --self-contained false

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app .
ENTRYPOINT ["dotnet", "backend.dll"]

