version: '3.3'

services:
  nuxt:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run dev
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "3000:3000"
  db: 
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    image: db_dev
    container_name: db_dev

