FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /db



COPY backend/*.sln .
COPY backend/*.csproj .

RUN dotnet restore --use-current-runtime

COPY backend/. .
RUN dotnet publish -c Release -o /app --use-current-runtime 

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app .
ENTRYPOINT ["dotnet", "API-Test.dll"]

